FROM python:3.8-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./db ./db
COPY ./shared ./shared
COPY ./sync ./sync
COPY ./main_shared_games_sync.py ./main_shared_games_sync.py

CMD [ "python3", "main_shared_games_sync.py" ]