apiVersion: v1
kind: Secret
metadata:
  name: secret-files
data:
  credentials.json: '{{ werf_secret_file "credentials.json" | b64enc }}'
  ca.pem: '{{ werf_secret_file "ca.pem" | b64enc }}'
  mongodb.pem: '{{ werf_secret_file "mongodb.pem" | b64enc }}'
