apiVersion: batch/v1
kind: CronJob
metadata:
  name: youtube-sync
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: youtube-sync
        spec:
          restartPolicy: Never
          containers:
            - name: python
              image: "{{ .Values.werf.image.youtube_sync }}"
              workingDir: /app
              env:
                - name: MONGO_URI
                  value: "{{ .Values.mongodb.uri }}"
                - name: MONGO_DB_NAME
                  value: '{{ eq .Values.werf.env "staging" | ternary .Values.mongodb.dbName.staging .Values.mongodb.dbName._default }}'
                - name: REDIS_URI
                  value: "redis://{{ .Release.Name }}-redis-master"
                - name: PROXY_URI
                  value: "{{ .Values.proxy.uri }}"
              volumeMounts:
                - name: secret-files
                  mountPath: "/app/secret"
                  readOnly: true
          volumes:
            - name: secret-files
              secret:
                secretName: secret-files
                optional: false
