redis:
  auth:
    enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false
    limits:
      memory: 128Mi
  master:
    disableCommands: []
    persistence:
      enabled: false
    limits:
      memory: 128Mi
